# Generated by Django 4.1.7 on 2023-03-14 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата рождения"
            ),
            preserve_default=False,
        ),
    ]
